"""Render `data/equity_curve.csv` as a self‑contained HTML page.

Uses only the standard library (no matplotlib).  The chart is drawn as
inline SVG so it opens in any browser without extra files.
"""

import csv
import html
import pathlib

DATA = pathlib.Path(__file__).resolve().parent / "data"
SRC  = DATA / "equity_curve.csv"
OUT  = DATA / "equity_curve.html"

# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------
rows = []
with SRC.open(encoding="utf-8") as f:
    for r in csv.DictReader(f):
        rows.append({
            "datetime": r["datetime"],
            "side":     r["side"],
            "ret":      float(r["ret"]),
            "cum_pnl":  float(r["cum_pnl"]),
        })

if not rows:
    raise SystemExit(f"No rows in {SRC}.  Run `python -m src.backtest` first.")

# ---------------------------------------------------------------------------
# Build polyline
# ---------------------------------------------------------------------------
n      = len(rows)
max_p  = max(r["cum_pnl"] for r in rows)
min_p  = min(r["cum_pnl"] for r in rows)
span   = max(max_p - min_p, 1e-9)

W, H, PAD = 1000, 400, 40
def to_xy(i, v):
    x = PAD + (W - 2 * PAD) * i / max(n - 1, 1)
    y = PAD + (H - 2 * PAD) * (1 - (v - min_p) / span)
    return x, y

points = " ".join(f"{x:.1f},{y:.1f}"
                  for x, y in (to_xy(i, r["cum_pnl"]) for i, r in enumerate(rows)))

# Buy / sell markers (every 50th trade keeps the SVG readable)
markers = []
for i, r in enumerate(rows):
    if i % max(1, n // 200) != 0:
        continue
    x, _ = to_xy(i, r["cum_pnl"])
    y_marker = H - PAD + 12 if r["side"] == "BUY" else PAD - 4
    color = "#16a34a" if r["side"] == "BUY" else "#dc2626"
    markers.append(
        f'<circle cx="{x:.1f}" cy="{y_marker:.1f}" r="2.5" fill="{color}" />'
    )
markers_svg = "\n      ".join(markers)

# ---------------------------------------------------------------------------
# Summary stats
# ---------------------------------------------------------------------------
win_rate = sum(1 for r in rows if r["ret"] > 0) / n
total    = rows[-1]["cum_pnl"]
avg_bps  = (sum(r["ret"] for r in rows) / n) * 10_000
n_buy    = sum(1 for r in rows if r["side"] == "BUY")
n_sell   = n - n_buy

# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------
PAGE = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Cerebrum Trader Bot – Equity Curve</title>
<style>
  :root {{ color-scheme: dark; }}
  body  {{ font: 14px/1.4 -apple-system, "Segoe UI", system-ui, sans-serif;
           margin: 0; padding: 24px; background: #0b0f17; color: #e5e7eb; }}
  h1    {{ font-size: 20px; margin: 0 0 4px; }}
  .sub  {{ color: #94a3b8; margin-bottom: 24px; }}
  .grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px;
           margin-bottom: 24px; }}
  .card {{ background: #111827; border: 1px solid #1f2937;
           border-radius: 8px; padding: 14px; }}
  .card .k {{ color: #94a3b8; font-size: 12px; text-transform: uppercase; letter-spacing: .05em; }}
  .card .v {{ font-size: 22px; font-weight: 600; margin-top: 4px; }}
  .pos  {{ color: #16a34a; }} .neg  {{ color: #dc2626; }}
  svg   {{ width: 100%; height: auto; background: #0f172a; border-radius: 8px; }}
  .axis {{ stroke: #1f2937; stroke-width: 1; }}
  .line {{ fill: none; stroke: #38bdf8; stroke-width: 1.4; }}
</style>
</head>
<body>
  <h1>Cerebrum Trader Bot – Back‑test Equity Curve</h1>
  <div class="sub">USD/EUR · synthetic 1‑hour candles · 2023‑01‑01 → 2025‑12‑31</div>

  <div class="grid">
    <div class="card"><div class="k">Trades</div><div class="v">{n:,}</div></div>
    <div class="card"><div class="k">Win‑rate</div><div class="v">{win_rate:.1%}</div></div>
    <div class="card"><div class="k">Avg P&amp;L (bps)</div>
      <div class="v {'pos' if avg_bps >= 0 else 'neg'}">{avg_bps:+.2f}</div></div>
    <div class="card"><div class="k">Total P&amp;L</div>
      <div class="v {'pos' if total >= 0 else 'neg'}">{total:+.2%}</div></div>
  </div>

  <svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg">
    <line class="axis" x1="{PAD}" y1="{PAD}" x2="{PAD}" y2="{H-PAD}" />
    <line class="axis" x1="{PAD}" y1="{H-PAD}" x2="{W-PAD}" y2="{H-PAD}" />
    <polyline class="line" points="{points}" />
    {markers_svg}
  </svg>

  <p style="margin-top:16px;color:#94a3b8;font-size:12px;">
    🟢 = BUY entry &nbsp; 🔴 = SELL entry &nbsp;
    Generated by <code>render_equity_curve.py</code>
  </p>
</body>
</html>
"""

OUT.write_text(PAGE, encoding="utf-8")
print(f"✅ Equity curve rendered → {OUT}")
print(f"   {n:,} trades · win‑rate {win_rate:.1%} · total P&L {total:+.2%}")